created registration form
krismutalapova/nysure_web_application pull request #4
Opened 2019-11-27 14:58 UTC by Pinelopi85

Hello team, I have adjusted the registration form for our needs. Please review and get back to me.

2019-11-27 15:58 UTC, elmenqui approved these changes
LGTM

2019-11-27 20:30 UTC, MeriM-dev approved these changes
LGTM!

2019-11-27 20:50 UTC, MeriM-dev commented on frontend/src/components/auth/RegisterForm.js
> +    const [telephone, setTelephone]=use
should this be `useState("");`?

2019-11-27 21:27 UTC, MeriM-dev requested changes

2019-11-27 21:27 UTC, MeriM-dev commented on frontend/src/components/auth/RegisterForm.js
> +                            value={name}
This should be `value={address}`

2019-11-27 21:27 UTC, MeriM-dev commented on frontend/src/components/auth/RegisterForm.js
> +                            value={name}
This should be `value={telephone}`

2019-11-28 13:44 UTC, MeriM-dev approved these changes

2019-11-28 15:11 UTC, merged